from enum import StrEnum


class Equipment(StrEnum):
    OVEN = "oven"
    STOVE = "stove"
    MICROWAVE = "microwave"
    GRILL = "grill"
    BARBECUE_GRILL = "barbecue_grill"
    PRESSURE_COOKER = "pressure_cooker"
    SLOW_COOKER = "slow_cooker"
    RICE_COOKER = "rice_cooker"
    AIR_FRYER = "air_fryer"
    BLENDER = "blender"
    IMMERSION_BLENDER = "immersion_blender"
    FOOD_PROCESSOR = "food_processor"
    STAND_MIXER = "stand_mixer"
    HAND_MIXER = "hand_mixer"
    TOASTER = "toaster"
    KETTLE = "kettle"
    LARGE_PAN = "large_pan"
    SAUCEPAN = "saucepan"
    FRYING_PAN = "frying_pan"
    WOK = "wok"
    DUTCH_OVEN = "dutch_oven"
    ROASTING_PAN = "roasting_pan"
    BAKING_SHEET = "baking_sheet"
    CASSEROLE_DISH = "casserole_dish"
    MIXING_BOWL = "mixing_bowl"
    CUTTING_BOARD = "cutting_board"
    CHEF_KNIFE = "chef_knife"
    PARING_KNIFE = "paring_knife"
    BREAD_KNIFE = "bread_knife"
    KITCHEN_SCISSORS = "kitchen_scissors"
    FORK = "fork"
    TEASPOON = "teaspoon"
    TABLESPOON = "tablespoon"
    WOODEN_SPOON = "wooden_spoon"
    SERVING_SPOON = "serving_spoon"
    LADLE = "ladle"
    CUP = "cup"
    MEASURING_CUP = "measuring_cup"
    MEASURING_SPOONS = "measuring_spoons"
    SPATULA = "spatula"
    WHISK = "whisk"
    TONGS = "tongs"
    PEELER = "peeler"
    GRATER = "grater"
    COLANDER = "colander"
    SIEVE = "sieve"
    ROLLING_PIN = "rolling_pin"
    CAN_OPENER = "can_opener"


class OperationalRequirement(StrEnum):
    """Canonical operational constraints elicited for every recipe."""

    GAS_OR_ELECTRIC = "gas_or_electric"
    FRIDGE_SPACE = "fridge_space"
    PREP_TIME = "prep_time"
    COUNTER_SPACE = "counter_space"
    STOVE_BURNERS = "stove_burners"